### ISSUE TITLE
Questões sobre Requisitos Não-Funcionais

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/ferias_detran_parteII#5]
A [documentação do projeto 01](https://github.com/JoaoGFarias/ferias_detran_parteII/blob/master/Projeto01.pdf) não especificou nenhum requisito não-funcional.

Então, vamos usar essa issue para trackear o que precisamos confirmar.
Levantei rapidamente alguns pontos; fiquem a vontade para expandir e comentar.

* Performace

  * Número total de funcionários;

  * Número máximo de funcionários por chefe;

  * Número de acessos simultâneos esperado;

  * Qual é o tempo de resposta aceitável para cada operação funcional?
´
* Segurança:

  * Será possível acessar o sistema fora da rede física de internet do DETRAN:

      * Se sim, o acesso pode ser feito apenas com usuário e senha ou será necessário uma VPN?

* Acessibilidade

   * Que tipos de usuários com dificuldades usarão o sistema?

* Privacidade de Dados

   * O sistema rodará em um ambiente do próprio DETRAN ou em um servidor externo?

        * Se externo, 
             * Que tipo de segurança legal deverá existir?
             * Que tipo de segurança computacional deverá existir?

* Recuperação de Desastres e Backup

     * Como o sistema deve se comportar em casos de desastres?
     * Qual é a estratégia de backup que será utilizada?

**Comment by filipegutemberg** [comment]
Performace

Número total de funcionários;

Além do que foi citado no documento do primeiro trabalho, existem os cargos comissionados que também é de responsabilidade do DETRAN agendar as férias, portanto o número de usuários do sistema está estimado em 1500 funcionários.

Número máximo de funcionários por chefe;

O maior setor do DETRAN-PE é a Unidade de fiscalização e controle com 170 funcionários.

Número de acessos simultâneos esperado;

Segundo informações da pessoa que toma conta das férias dos funcionários e a modelagem BPMN que fizemos no primeiro trabalho, os funcionários têm aproximadamente dois meses para realizar o agendamento de férias, que seriam outubro e novembro. A demanda acontece perto do fim do prazo de entrega das escalas de férias, quando cerca de 20% do quadro de funcionários realiza o agendamento.

Qual é o tempo de resposta aceitável para cada operação funcional?

Os sistemas do DETRAN-PE, em condições normais, têm um tempo de resposta em geral de dois segundos ou menos.

Segurança:

Será possível acessar o sistema fora da rede física de internet do DETRAN:

Não vejo esta necessidade. O DETRAN não possui home office e a maioria dos funcionários ativos estão sempre  em contato com as dependências do órgão. A excepcionalidade fica por conta dos servidores cedidos (que são do DETRAN, mas trabalham em outros órgãos). Esses casos não devem ser cobertos pelo sistema, pois é necessário a autorização da chefia do cedido do órgão em  que ele está trabalhando. 

Se sim, o acesso pode ser feito apenas com usuário e senha ou será necessário uma VPN?

Não se aplica.

Acessibilidade

Que tipos de usuários com dificuldades usarão o sistema?
Não se aplica.
___________________________________________________________________________
|Privacidade de Dados
|
|O sistema rodará em um ambiente do próprio DETRAN ou em um servidor externo?
|
|
|Se externo,
|Que tipo de segurança legal deverá existir?
|Que tipo de segurança computacional deverá existir?
|Recuperação de Desastres e Backup
|
|
|Estas questões precisam ser levantadas com o setor de informática do DETRAN.
|__________________________________________________________________________
Como o sistema deve se comportar em casos de desastres?

Os dados de férias não podem ser perdidos em hipótese alguma. Por não ser um serviço de alta criticidade, o é tolerável que o sistema fique fora em casos eventuais, porém não deve acontecer em época de alta demanda.

Qual é a estratégia de backup que será utilizada?

Com base no exposto, a equipe do projeto deverá discutir a melhor solução de backup.
